### ISSUE TITLE
Cards by card type

### ISSUE THREAD

**Issue by yads** [madarasz/NetrunnerMeta#2]
Not sure if this is already a feature, but a lot of the time I'm curious to find out what are the top played Sentries for example, or top played breakers. It would be very useful to tune a deck to the current meta if you were able to get this info.

**Comment by madarasz** [comment]
http://www.knowthemeta.com/DPStats/Council%20of%20the%20Crest/#ice

So you drill down by cardpool ("Tournament Drilldown") and select the ICE/breakers tab.
